export default {
  products: [
    {
      id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/img/product_1.png",
      price: 60,
      brand: "US Polo",
      rating: 4.5,
      numReviews: 10,
      year: 2020,
      sale: false,
    },
    {
      id: "2",
      name: "Big Shirt",
      category: "Shirts",
      image: "/img/product_1.png",
      price: 30,
      brand: "US Polo",
      rating: 3,
      numReviews: 4,
      year: 2019,
      sale: true,
    },
    {
      id: "3",
      name: "Small Pants",
      category: "Pants",
      image: "/img/product_1.png",
      price: 32,
      brand: "US Polo",
      rating: 2,
      numReviews: 11,
      year: 2020,
      sale: true,
    },
  ],
};
